### ISSUE TITLE
[question] Does this support STS credentials?

### ISSUE THREAD

**Issue by jonasfj** [luser/sccache2#2]
AWS temporary credentials STS comes with a SessionToken that must be attached to all requests.
It would be rather nice if sscache was to supports this.

Note: I know this is work in progress. But ideally the readme should document the command line arguments, so it's easy to deploy and configure.

**Comment by luser** [comment]
It doesn't actually support any of S3 yet, but I will take a look at this once I get to that point. :) I was planning on just using `rusoto`, which seems to be a Rust clone of boto: https://github.com/rusoto/rusoto , so you might check their docs to see if they support it. If not, implementing it there would let us use it here.

**Comment by luser** [comment]
Yes, this supports credentials that use a SessonToken:
https://github.com/luser/sccache2/blob/8f664d89cc5e060e32a65c9d1dda6376ff4af4a7/src/simples3/s3.rs#L108

This is working on the buildbot builders currently, fetching credentials via IAM.
