### ISSUE TITLE
Auto-detect S3 bucket region instead of requiring `SCCACHE_REGION`

### ISSUE THREAD

**Issue by luser** [luser/sccache2#21]
The Python implementation takes `SCCACHE_BUCKET` and somehow uses the right region, or there's something I'm missing. It's possible to detect the region for a bucket (HEAD bucket will return it in the headers), but I can't figure out a straightforward way to do this in rusoto.

@glandium is there anything I'm missing here in the Python implementation?

**Comment by glandium** [comment]
The python implementation respects the boto config. I don't remember if we have a boto config that changes the calling format or the host part, but the default for boto is that it tries $bucket.s3.amazonaws.com.

As a matter of fact:
```
$ host mozilla-releng-s3-cache-us-west-1-try.s3.amazonaws.com
mozilla-releng-s3-cache-us-west-1-try.s3.amazonaws.com is an alias for s3-us-west-1-w.amazonaws.com.
s3-us-west-1-w.amazonaws.com has address 54.231.236.31
```

So we probably are using the default calling format.

**Comment by glandium** [comment]
It looks like a serious deficiency in the Rusoto API that the region is apparently required for S3. If you ask me, Rusoto is very much bloated by the fact it supports many more things than just retrieving and uploading files to S3 (like, creating buckets).

**Comment by glandium** [comment]
rust-s3 (https://crates.io/crates/rust-s3) looks simpler and allows not to give the region name. It's new, but derived from https://github.com/rust-lang/crates.io/blob/master/src/s3/lib.rs which is the code behind crates.io.

I'm almost tempted to say we should just import the crates.io code. It's small, self contained, and simple enough. It doesn't have a GET, but we don't actually need a GET through S3. In fact, we don't want GET through S3 APIs, which, as I see now, is what sccache2 is doing. Doing so adds a significant latency to requests. At least that was true in python.

**Comment by luser** [comment]
The only thing I'd miss from Rusoto is the automatic credential detection. I'd hate to have to duplicate that. I guess we could just copy-paste the credentials bit out of rusoto: https://github.com/rusoto/rusoto/blob/master/src/credential.rs It doesn't look like it depends on much else in the crate except error.rs (and that wouldn't be hard to fix).

**Comment by luser** [comment]
That crates.io s3 code looks pretty reasonable, although it's using the curl crate, which is going to make things even more of a hassle on Windows. It's pretty simple, so I'm sure I could rewrite it to use hyper, which might not be terrible.

**Comment by luser** [comment]
I imported that crates.io code, as well as credential.rs from rusoto:
https://github.com/luser/sccache2/commit/657cb895f12bb0e51f950b6d62b1ff24a59ad9a8

It works in local testing, and fixes the specific issue at hand.
