### ISSUE TITLE
Allow logging to file

### ISSUE THREAD

**Issue by luser** [luser/sccache2#7]
The log / env_logger crates are great and easy to use, but I'd like to have the ability to log to a file so that logging from the server process is useful. Someone pointed me at this crate which might be the way to go:
https://github.com/daboross/fern-rs

**Comment by F3real** [comment]
Hi Ted,

I browsed through code a little bit and I was just thinking about asking you which issue should I try too do 1st when I have gotten this email.

I'll look at at fern-rs and see what  I can do. Btw your rust seems really good.

21.06.2016, 12:55, "Ted Mielczarek" <notifications@github.com>:

**Comment by luser** [comment]
Thanks! I was just cleaning up some old browser tabs I had hanging around and fern-rs was in one of them. This would be a great place for you to start.
